image: debian:buster
before_script:
- 'export DEBIAN_FRONTEND=noninteractive
     && apt-get update -qq
     && apt-get -qy install git i18nspector'
lint-po:
  script:
  - git clone https://gitlab.tails.boum.org/tails/jenkins-tools.git /tmp/jenkins-tools
  - /tmp/jenkins-tools/slaves/lint_po
