image: debian:buster

before_script:
- export DEBIAN_FRONTEND=noninteractive
- apt-get update -qq

lint-po:
  image: debian:testing
  script:
  - apt-get -qy install git i18nspector
  - git clone https://gitlab.tails.boum.org/tails/jenkins-tools.git /tmp/jenkins-tools
  - /tmp/jenkins-tools/slaves/lint_po

check-po-msgfmt:
  script:
  - apt-get -qy install python3 gettext
  - ./bin/check-po-msgfmt
