---
# TODO: see #18123 for better solution to apparmor-profiles
# since this is one of the most powerful profiles, it must be one of the first to be migrated
- hosts:
    - '10.200.1.10'
  commands:
    SAVECONF:
      - ''
    GETINFO:
      - 'status/bootstrap-phase'
      - 'status/circuit-established'
      - 'version'
  confs:
    UseBridges: ['', '.*']
    Bridge: ['', '.*']
    Socks4Proxy: ['', '.*']
    Socks5Proxy: ['', '.*']
    HttpsProxy: ['', '.*']
    Socks5ProxyUsername: ['', '.*']
    Socks5ProxyPassword: ['', '.*']
    HttpsProxyAuthenticator: ['', '.*']
    ReachableAddresses: ['', '.*']
    DisableNetwork: ['"0"', '"1"']
    __owningcontrollerprocess:
  events:
    STATUS_CLIENT:
    STATUS_SERVER:
    SIGNAL:
    CONF_CHANGED:
    NOTICE:
    WARN:
    ERR:
